# Generated by Django 4.2.7 on 2023-12-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_teacher_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='content',
            field=models.CharField(max_length=20000),
        ),
    ]
